# POST /submit-form
POST https://burgerplanet.hasura.app/api/rest/formulir
Content-Type: application/json
x-hasura-admin-secret: kp2SL81BuVRoK4IhX1yGrSauTX9Ng5HyPIb7Vu3rURZK770dPTdx1puj6jhCAxjz

{
    "nama": "{{nama}}",
    "barang": "{{barang}}",
    "quantity": "{{quantity}}"
}
